export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_IMAGES = 'FETCH_IMAGES'
export const FETCH_IMAGE_FILES = 'FETCH_IMAGE_FILES'
export const ADD_POST = 'ADD_POST'
export const REPLACE_POST = 'REPLACE_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_FILTER = 'SET_FILTER'

//export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SET_USER_STATUS = 'SET_USER_STATUS'
